apiVersion: v1
kind: PersistentVolume
metadata:
  name: product-postgres-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/product-postgres"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-postgres
  template:
    metadata:
      labels:
        app: product-postgres
    spec:
      containers:
      - name: product-postgres
        image: postgres
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: password
          - name: POSTGRES_DB
            value: products
        ports:
          - containerPort: 5432
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: product-postgres-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: product-postgres-service
spec:
  selector:
    app: product-postgres
  ports:
    - name: product-postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
